---
- hosts: all
  gather_facts: false
  tasks:
    - name: Get OS release information
      shell: cat /etc/os-release
      register: os_release

    - name: Extract PRETTY_NAME
      set_fact:
        pretty_name: "{{ os_release.stdout | regex_search('PRETTY_NAME=\"(.+?)\"', '\\1') }}"

    - name: Display PRETTY_NAME
      debug:
        msg: "The pretty name is: {{ pretty_name }}"
